# Generated by Django 5.2.8 on 2025-11-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("case_api", "0002_alter_case_project"),
        ("case_ui", "0001_initial"),
        ("django_q", "0014_schedule_cluster"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="套件名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="套件描述"),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[("O", "单次执行"), ("C", "计划任务"), ("W", "webhook")],
                        default="O",
                        max_length=30,
                        verbose_name="运行类型",
                    ),
                ),
                (
                    "cron",
                    models.CharField(blank=True, max_length=30, verbose_name="cron表达式"),
                ),
                (
                    "hook_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="webhook密钥"
                    ),
                ),
                (
                    "case_api_list",
                    models.ManyToManyField(blank=True, to="case_api.case"),
                ),
                ("case_ui_list", models.ManyToManyField(blank=True, to="case_ui.case")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_q.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="用例路径")),
                ("is_pass", models.BooleanField(default=False, verbose_name="测试通过")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "初始化"),
                            (1, "准备开始"),
                            (2, "正在执行"),
                            (3, "正在生成报告"),
                            (4, "执行完毕"),
                            (-1, "执行出错"),
                        ],
                        default=0,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="suite.suite"
                    ),
                ),
            ],
        ),
    ]
