# Generated by Django 5.1.7 on 2025-04-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_profile_username_profile_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "用户列表", "verbose_name_plural": "用户列表"},
        ),
    ]
