# Generated by Django 4.2.16 on 2024-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="name",
            field=models.CharField(
                default="未命名", max_length=32, verbose_name="角色名称"
            ),
        ),
    ]
