# Generated by Django 5.2.8 on 2026-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.CharField(max_length=256, verbose_name="项目地址"),
        ),
    ]
