# Generated by Django 5.2.8 on 2026-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_add_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.CharField(default="", max_length=256, verbose_name="项目地址"),
        ),
    ]
