# Generated by Django 5.2.8 on 2026-03-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_line", "0001_initial"),
        ("project", "0005_config_updated_at_config_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
    ]
