# Generated by Django 5.2.8 on 2026-03-30 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_add_product_line_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.SmallIntegerField(
                choices=[(0, "普通"), (1, "重要"), (2, "紧急")], default=0, verbose_name="优先级"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "规划中"),
                    ("active", "进行中"),
                    ("testing", "测试中"),
                    ("done", "已完成"),
                    ("archived", "已归档"),
                ],
                default="planning",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：Sprint 2024-Q1、v2.5.0",
                        max_length=64,
                        verbose_name="迭代名称",
                    ),
                ),
                ("goal", models.TextField(blank=True, default="", verbose_name="迭代目标")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "规划中"),
                            ("active", "进行中"),
                            ("reviewing", "评审中"),
                            ("done", "已完成"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "迭代",
                "verbose_name_plural": "迭代",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="需求标题")),
                ("desc", models.TextField(blank=True, default="", verbose_name="需求描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待开发"),
                            ("in_dev", "开发中"),
                            ("in_test", "测试中"),
                            ("in_review", "评审中"),
                            ("done", "已完成"),
                            ("rejected", "已驳回"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(0, "低"), (1, "中"), (2, "高"), (3, "紧急")],
                        default=1,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "estimate",
                    models.SmallIntegerField(default=0, verbose_name="预估工时(h)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="project.sprint",
                        verbose_name="所属迭代",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求",
                "verbose_name_plural": "需求",
                "ordering": ["-priority", "due_date"],
            },
        ),
    ]
