# Generated by Django 4.2.16 on 2026-04-01 12:34

from django.db import migrations, models
import django.db.models.deletion


def backfill_sprint_product_line(apps, schema_editor):
    Sprint = apps.get_model('project', 'Sprint')
    for s in Sprint.objects.filter(product_line__isnull=True).select_related('project'):
        if s.project_id and getattr(s.project, 'product_line_id', None):
            s.product_line_id = s.project.product_line_id
            s.save(update_fields=['product_line'])


class Migration(migrations.Migration):

    dependencies = [
        ("product_line", "0001_initial"),
        ("project", "0008_projectcaseref_projectsuiteref_sprintcaseref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprints",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprints",
                to="project.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.RunPython(backfill_sprint_product_line, migrations.RunPython.noop),
    ]
