# Generated by Django 4.2.16 on 2026-04-01 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0009_sprint_product_line_alter_sprint_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_sprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="迭代负责人",
            ),
        ),
    ]
