# Generated by Django 4.2.16 on 2024-12-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="接口名称")),
                ("method", models.CharField(max_length=8, verbose_name="")),
                ("url", models.CharField(max_length=255, verbose_name="")),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        max_length=10240,
                        null=True,
                        verbose_name="查询字符串",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="表单参数"
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="json参数"
                    ),
                ),
                (
                    "cookies",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="Cookies"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="请求头"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用例名称")),
                (
                    "alluer",
                    models.JSONField(blank=True, null=True, verbose_name="Allure标注"),
                ),
                (
                    "api_args",
                    models.JSONField(
                        blank=True, null=True, verbose_name="接口用例参数"
                    ),
                ),
                (
                    "extract",
                    models.JSONField(blank=True, null=True, verbose_name="数据提取"),
                ),
                ("validate", models.JSONField(verbose_name="断言")),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_api.endpoint",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
