# Generated by Django 5.1.7 on 2025-05-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_api",
                to="project.project",
            ),
        ),
    ]
