# Generated by Django 4.2.16 on 2024-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(
                default="你是猪", max_length=32, verbose_name="昵称"
            ),
        ),
    ]
