# Generated by Django 5.1.7 on 2025-05-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_profile_avatar_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="avatar",
            new_name="avatar_url",
        ),
    ]
