# Generated by Django 5.1.7 on 2025-05-29 11:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_avatar_profile_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="avatar",
            field=models.FileField(
                upload_to=account.models.user_head_img_path, verbose_name="用户头像"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_url",
            field=models.CharField(max_length=512, verbose_name="头像地址"),
        ),
    ]
