# Generated by Django 5.2.8 on 2026-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_avatar_avatar_alter_profile_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
    ]
