# Generated by Django 5.2.8 on 2026-03-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_avatar_created_at_profile_created_at"),
        ("system", "0008_permission_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="system.department",
                verbose_name="所属部门",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="system.position",
                verbose_name="职位",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_url",
            field=models.CharField(default="", max_length=512, verbose_name="头像地址"),
        ),
    ]
