# Generated by Django 5.1.7 on 2025-11-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="department",
        ),
        migrations.RemoveField(
            model_name="role",
            name="position",
        ),
    ]
