# Generated by Django 5.1.7 on 2025-11-11 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_userrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRole",
            new_name="User_Role",
        ),
    ]
