# Generated by Django 5.1.7 on 2025-11-11 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_rename_userrole_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "角色列表", "verbose_name_plural": "角色列表"},
        ),
        migrations.AlterModelOptions(
            name="user_role",
            options={"verbose_name": "用户角色关系", "verbose_name_plural": "用户角色关系"},
        ),
        migrations.RemoveField(
            model_name="role",
            name="user",
        ),
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                related_name="roles",
                through="system.User_Role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="user_role",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_role",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="system.role",
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="user_role",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user_role",
            unique_together={("user", "role")},
        ),
    ]
