# Generated by Django 5.2.8 on 2026-03-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_department_created_at_position_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="权限码"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="权限名称")),
                ("module", models.CharField(max_length=32, verbose_name="所属模块")),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限列表",
                "ordering": ["module", "code"],
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "部门", "verbose_name_plural": "部门列表"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "职位", "verbose_name_plural": "职位列表"},
        ),
        migrations.AddField(
            model_name="department",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_departments",
                to="system.role",
                verbose_name="默认角色",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="leader",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="负责人",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="system.permission",
                verbose_name="权限",
            ),
        ),
    ]
