# Generated by Django 5.2.8 on 2026-03-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0003_endpoint_requires_provides"),
        ("case_ui", "0001_initial"),
        ("django_q", "0014_schedule_cluster"),
        ("suite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suite",
            name="case_api_list",
        ),
        migrations.RemoveField(
            model_name="suite",
            name="case_ui_list",
        ),
        migrations.AlterField(
            model_name="suite",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_q.schedule",
            ),
        ),
        migrations.CreateModel(
            name="SuiteCaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[("API", "API用例"), ("UI", "UI用例")],
                        default="API",
                        max_length=8,
                        verbose_name="用例类型",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="执行顺序")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "env_override",
                    models.JSONField(
                        blank=True,
                        help_text="运行时覆盖用例参数，格式与 api_args 相同",
                        null=True,
                        verbose_name="参数覆盖",
                    ),
                ),
                (
                    "case_api",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_items",
                        to="case_api.case",
                        verbose_name="API用例",
                    ),
                ),
                (
                    "case_ui",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_items",
                        to="case_ui.case",
                        verbose_name="UI用例",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_case_items",
                        to="suite.suite",
                        verbose_name="所属套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "套件用例项",
                "verbose_name_plural": "套件用例项",
                "ordering": ["order", "id"],
            },
        ),
    ]
