# Generated by Django 5.2.8 on 2026-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0002_suite_case_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="runresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="suitecaseitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
    ]
