# Generated by Django 5.2.8 on 2026-03-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_config_created_at"),
        ("suite", "0003_runresult_created_at_suite_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="suite_variables",
            field=models.JSONField(
                blank=True,
                help_text='键值对，如 {"api_host": "test.example.com"}，可在用例参数中用 ${api_host} 引用',
                null=True,
                verbose_name="套件变量",
            ),
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="环境名称")),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="如 https://test.example.com，留空则不替换接口 host",
                        max_length=255,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        help_text='注入到所有请求的请求头，如 {"X-Env": "test"}',
                        null=True,
                        verbose_name="全局请求头",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        help_text='键值对，如 {"host": "test.example.com"}',
                        null=True,
                        verbose_name="环境变量",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "运行环境",
                "verbose_name_plural": "运行环境",
                "ordering": ["project", "name"],
            },
        ),
        migrations.AddField(
            model_name="suite",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suites",
                to="suite.environment",
                verbose_name="运行环境",
            ),
        ),
        migrations.CreateModel(
            name="GlobalVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, verbose_name="变量名")),
                (
                    "value",
                    models.CharField(blank=True, max_length=1024, verbose_name="变量值"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_variables",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局变量",
                "verbose_name_plural": "全局变量",
                "ordering": ["project", "key"],
                "unique_together": {("project", "key")},
            },
        ),
    ]
