# Generated by Django 5.2.8 on 2026-03-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0004_add_environment_and_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="urls",
            field=models.JSONField(
                blank=True,
                help_text='多服务 URL，格式: [{"name": "用户服务", "url": "https://user.example.com", "var": "user_host"}]',
                null=True,
                verbose_name="服务 URL 列表",
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="base_url",
            field=models.CharField(
                blank=True,
                help_text="单服务 base_url，建议迁移到 urls 字段",
                max_length=255,
                verbose_name="Base URL（兼容旧字段）",
            ),
        ),
    ]
