# Generated by Django 5.2.8 on 2026-03-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_config_created_at"),
        ("suite", "0006_globalvariable_environment_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalvariable",
            options={
                "ordering": ["environment", "key"],
                "verbose_name": "全局变量",
                "verbose_name_plural": "全局变量",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="全局唯一标识，如 user-site、order-service",
                        max_length=64,
                        unique=True,
                        verbose_name="服务标识",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="服务名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
                "ordering": ["project", "name"],
            },
        ),
    ]
