# Generated by Django 5.2.8 on 2026-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0007_add_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="fail_strategy",
            field=models.CharField(
                choices=[("continue", "继续执行"), ("stop", "立即停止")],
                default="continue",
                help_text="某条用例失败后，套件是继续执行还是立即停止",
                max_length=16,
                verbose_name="失败策略",
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="retry_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="用例失败后最多重试次数，0 表示不重试", verbose_name="重试次数"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="retry_delay",
            field=models.FloatField(
                default=1.0, help_text="每次重试前等待秒数", verbose_name="重试间隔(秒)"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="timeout_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="单条用例最大执行秒数，0 表示不限制", verbose_name="用例超时时间(秒)"
            ),
        ),
    ]
