# Generated by Django 5.2.8 on 2026-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0008_add_suite_execution_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitecaseitem",
            name="role",
            field=models.CharField(
                choices=[("setup", "前置操作"), ("main", "正式用例"), ("teardown", "后置操作")],
                default="main",
                help_text="setup=前置操作，main=正式用例，teardown=后置操作",
                max_length=16,
                verbose_name="用例角色",
            ),
        ),
    ]
