# Generated by Django 5.2.8 on 2026-03-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0009_add_suite_case_item_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suitecaseitem",
            name="role",
        ),
    ]
