# Generated by Django 5.2.8 on 2026-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0010_remove_suitecaseitem_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitecaseitem",
            name="role",
            field=models.CharField(
                choices=[("setup", "前置操作"), ("main", "正式用例"), ("teardown", "后置操作")],
                default="main",
                max_length=16,
                verbose_name="执行阶段",
            ),
        ),
    ]
