# Generated by Django 5.2.8 on 2026-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0011_add_suitecaseitem_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="suite_headers",
            field=models.JSONField(
                blank=True,
                help_text='注入到本套件所有请求的请求头，如 {"Authorization": "Bearer ${token}"}，优先级高于环境 headers',
                null=True,
                verbose_name="套件请求头",
            ),
        ),
    ]
