# Generated by Django 5.2.8 on 2026-03-14 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0012_add_suite_headers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suite_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
        migrations.AddField(
            model_name="suite",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suite_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后修改人",
            ),
        ),
    ]
