# Generated by Django 4.2.16 on 2026-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0013_add_suite_created_by_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="mock_rules",
            field=models.JSONField(
                blank=True,
                help_text="Mock 拦截规则列表，套件执行时自动启用",
                null=True,
                verbose_name="Mock 规则",
            ),
        ),
    ]
