# Generated by Django 4.2.16 on 2026-03-24 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_add_product_line_fk"),
        ("suite", "0014_add_mock_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users",
                    models.PositiveIntegerField(default=10, verbose_name="并发用户数"),
                ),
                (
                    "spawn_rate",
                    models.PositiveIntegerField(
                        default=1, verbose_name="每秒启动用户数"
                    ),
                ),
                (
                    "run_time",
                    models.PositiveIntegerField(
                        default=60, verbose_name="持续时间(秒)"
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 https://api.example.com，留空则从环境配置读取",
                        max_length=255,
                        verbose_name="目标Host",
                    ),
                ),
                (
                    "case_ids",
                    models.JSONField(
                        blank=True,
                        help_text="指定要压测的用例，为空则使用套件全部用例",
                        null=True,
                        verbose_name="用例ID列表",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("done", "已完成"),
                            ("stopped", "已停止"),
                            ("error", "执行出错"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Locust 进程 PID"
                    ),
                ),
                (
                    "work_dir",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="工作目录"
                    ),
                ),
                ("error_msg", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        help_text="{'total_requests': N, 'failure_rate': 0.02, 'avg_response_time': 120, ...}",
                        null=True,
                        verbose_name="汇总统计",
                    ),
                ),
                (
                    "stats_data",
                    models.JSONField(
                        blank=True,
                        help_text="[{ts, rps, avg_rt, failures}, ...]",
                        null=True,
                        verbose_name="详细统计数据（时序）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_tests",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_tests",
                        to="suite.suite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能测试",
                "verbose_name_plural": "性能测试列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
