# Generated by Django 4.2.16 on 2026-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0015_performance_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetest",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="自定义名称，留空则展示套件名称",
                max_length=128,
                verbose_name="压测名称",
            ),
        ),
    ]
