# Generated by Django 4.2.16 on 2026-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0017_perf_config_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="suitecaseitem",
            name="post_script",
            field=models.TextField(
                blank=True,
                default="",
                help_text='在本用例执行后运行的 Python 脚本，可读取 response/ctx，例如: ctx["user_id"] = response.get("id")',
                verbose_name="后置脚本",
            ),
        ),
        migrations.AddField(
            model_name="suitecaseitem",
            name="pre_script",
            field=models.TextField(
                blank=True,
                default="",
                help_text='在本用例执行前运行的 Python 脚本，可读写上下文变量 ctx，例如: ctx["token"] = "abc"',
                verbose_name="前置脚本",
            ),
        ),
    ]
