# Generated by Django 4.2.16 on 2026-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0018_add_pre_post_script"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suitecaseitem",
            name="post_script",
        ),
        migrations.RemoveField(
            model_name="suitecaseitem",
            name="pre_script",
        ),
    ]
