# Generated by Django 5.2.8 on 2026-03-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_line", "0001_initial"),
        ("suite", "0020_add_dataset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="runresult",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="run_results",
                to="product_line.productline",
            ),
        ),
        migrations.AddField(
            model_name="runresult",
            name="scope_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="执行域ID"
            ),
        ),
        migrations.AddField(
            model_name="runresult",
            name="scope_type",
            field=models.CharField(
                choices=[("project", "项目"), ("sprint", "迭代")],
                default="project",
                max_length=16,
                verbose_name="执行域类型",
            ),
        ),
        migrations.AddField(
            model_name="runresult",
            name="snapshot_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="快照ID"
            ),
        ),
        migrations.AddField(
            model_name="runresult",
            name="trigger_source",
            field=models.CharField(
                default="manual", max_length=16, verbose_name="触发来源"
            ),
        ),
        migrations.AddField(
            model_name="suite",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suites",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
        migrations.CreateModel(
            name="ExecutionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_type", models.CharField(max_length=16)),
                ("scope_id", models.PositiveIntegerField()),
                ("suite_name", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_snapshots",
                        to="product_line.productline",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_snapshots",
                        to="suite.suite",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionCaseSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.PositiveIntegerField()),
                ("case_name", models.CharField(max_length=64)),
                ("case_version", models.PositiveIntegerField(default=1)),
                ("payload_json", models.JSONField(default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_snapshots",
                        to="suite.executionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_type", models.CharField(blank=True, default="", max_length=16)),
                ("scope_id", models.PositiveIntegerField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("success", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                (
                    "error_file",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to="product_line.productline",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
