# Generated by Django 4.2.16 on 2026-04-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_sprint_updated_by"),
        ("suite", "0021_runresult_product_line_runresult_scope_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runresult",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="suite",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
            ),
        ),
    ]
