# Generated by Django 4.2.16 on 2026-04-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0015_ensure_suite_schedule_column"),
        ("suite", "0032_backfill_runresult_execution_log"),
    ]

    operations = []
