[pytest]
; addopts = -vs -k "django"
; addopts = -vs --alluredir=temps --clean-alluredir -vv -s -p no:yaml -p no:django
; testpaths = ./testcases
; python_files = test_*.py
; python_class = Test*
; mark =
;     smoke: 冒烟
;     user: 用户
;     order: 订单
;     master: 师傅

;
; markers =
;     new_post
;     new_reply
;
; disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
;
; xlsx_meta_column_name = 关键字

# 环境配置
[base_url]
user-site = https://user-site-api.wanshifu.com