[pytest]
# 配置 pytest 收集测试用例的规则
addopts = -vs
# 指定测试用例目录
testpaths = testcases
# 匹配 Python 测试文件和 YAML 测试文件
python_files = test_*.py test_*.yaml *.yaml
# 匹配测试类
python_class = Test*
# 匹配测试函数
python_functions = test_*
