# Generated by Django 4.2.16 on 2026-04-08 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0011_sprint_updated_by"),
        ("product_line", "0001_initial"),
        ("suite", "0032_backfill_runresult_execution_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "engine_type",
                    models.CharField(
                        choices=[("playwright", "Playwright")],
                        default="playwright",
                        max_length=32,
                        verbose_name="执行引擎",
                    ),
                ),
                (
                    "repo_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="仓库地址"
                    ),
                ),
                (
                    "local_repo_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="本地仓库路径"
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(
                        blank=True, default="main", max_length=100, verbose_name="默认分支"
                    ),
                ),
                (
                    "install_command",
                    models.CharField(
                        blank=True,
                        default="npm install",
                        max_length=500,
                        verbose_name="安装命令",
                    ),
                ),
                (
                    "test_command",
                    models.CharField(
                        blank=True,
                        default="npx playwright test",
                        max_length=500,
                        verbose_name="默认测试命令",
                    ),
                ),
                (
                    "report_dir",
                    models.CharField(
                        blank=True,
                        default="playwright-report",
                        max_length=255,
                        verbose_name="报告目录",
                    ),
                ),
                (
                    "results_dir",
                    models.CharField(
                        blank=True,
                        default="test-results",
                        max_length=255,
                        verbose_name="结果目录",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_projects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_projects",
                        to="product_line.productline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_projects",
                        to="project.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_projects_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("product_line", "name")},
            },
        ),
        migrations.CreateModel(
            name="AutomationSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="套件名称")),
                (
                    "suite_path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="执行路径"
                    ),
                ),
                (
                    "command_override",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="自定义命令"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "automation_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suites",
                        to="automation.automationproject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_suites_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_suites_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("automation_project", "name")},
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        default="manual", max_length=32, verbose_name="触发来源"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("error", "异常"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="分支"
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="执行命令"
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Base URL"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(blank=True, default=dict, verbose_name="变量"),
                ),
                (
                    "workdir",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="工作目录"
                    ),
                ),
                (
                    "log_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="日志路径"
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="报告路径"
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="结果详情"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs",
                        to="suite.environment",
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_runs",
                        to="product_line.productline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs",
                        to="project.project",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automation.automationsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
