# Generated by Django 5.2.8 on 2026-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
    ]
