# Generated by Django 4.2.16 on 2026-04-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_line", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0011_sprint_updated_by"),
        ("case_ui", "0002_case_created_at_element_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_ui_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="entry_url",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="入口地址"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="extract",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="数据提取"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="platform",
            field=models.CharField(
                choices=[("web", "Web"), ("app", "App")],
                default="web",
                max_length=16,
                verbose_name="平台类型",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="post_script",
            field=models.TextField(blank=True, default="", verbose_name="后置脚本"),
        ),
        migrations.AddField(
            model_name="case",
            name="pre_script",
            field=models.TextField(blank=True, default="", verbose_name="前置脚本"),
        ),
        migrations.AddField(
            model_name="case",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ui_cases",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ui_cases",
                to="project.requirement",
                verbose_name="关联需求",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ui_cases",
                to="project.sprint",
                verbose_name="所属迭代",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_ui_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后修改人",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="validate",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="断言规则"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="版本号"),
        ),
        migrations.AlterField(
            model_name="case",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_ui",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="steps",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="用例步骤"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="usefixtures",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="fixture列表"
            ),
        ),
    ]
