# Generated by Django 4.2.16 on 2026-04-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suite", "0032_backfill_runresult_execution_log"),
        ("case_ui", "0003_case_created_by_case_entry_url_case_extract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRunHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="是否成功")),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "assertions",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="断言结果"
                    ),
                ),
                (
                    "extracted",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="提取结果"
                    ),
                ),
                (
                    "screenshots",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="截图列表"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="执行时间"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_histories",
                        to="case_ui.case",
                        verbose_name="UI用例",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ui_case_run_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ui_case_histories",
                        to="suite.environment",
                        verbose_name="运行环境",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
