# Generated by Django 4.2.16 on 2024-10-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.IntegerField(default=1, verbose_name="商品质量")),
                ("attitude", models.IntegerField(default=1, verbose_name="客服态度")),
                ("speed", models.IntegerField(default=1, verbose_name="物流速度")),
                (
                    "text",
                    models.TextField(default="", max_length=150, verbose_name="意见反馈"),
                ),
                ("anonymous", models.BooleanField(default=True, verbose_name="是否匿名")),
            ],
        ),
    ]
