# Generated by Django 4.2.16 on 2024-10-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0002_alter_feedback_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="feedback",
            table="rating",
        ),
    ]
