# Generated by Django 4.2.16 on 2024-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0003_alter_feedback_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="feedback",
            table="feedback",
        ),
    ]
