# Generated by Django 4.2.16 on 2024-10-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0004_alter_feedback_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                ("email", models.CharField(max_length=100, verbose_name="邮箱")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
