# Generated by Django 4.2.16 on 2024-10-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0005_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="MyUser",
        ),
        migrations.AlterModelTable(
            name="myuser",
            table="myuser",
        ),
    ]
