# Generated by Django 4.2.16 on 2024-10-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0006_rename_user_myuser_alter_myuser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="beifan.myuser",
            ),
        ),
    ]
