# Generated by Django 4.2.16 on 2024-10-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0008_alter_feedback_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-id"]},
        ),
    ]
