# Generated by Django 4.2.16 on 2024-11-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beifan", "0009_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-id"],
                "verbose_name": "评价列表",
                "verbose_name_plural": "评价列表",
            },
        ),
    ]
