# Auto-generated by Tesla Performance Test
# Suite: 有登录前置的套件(取执行中的token) (id=4)
# Cases: ['web端登录密码正确', 'web端订单列表', '售后列表功能正常']

import json
from locust import HttpUser, task, between, events


class TeslaUser(HttpUser):
    """Tesla 性能测试用户"""
    host = "https://user-site-api.wanshifu.com"
    wait_time = between(1.0, 3.0)

    def on_start(self):
        """每个虚拟用户启动时初始化上下文"""
        self._ctx = {}

    @task
    def run_scenario(self):
        """执行测试场景（按用例顺序执行）"""
        # 用例: web端登录密码正确
        with self.client.post("/user/security/login", name="web\u7aef\u767b\u5f55\u5bc6\u7801\u6b63\u786e", headers={"content-type": "application/x-www-form-urlencoded"}, data={"principal": "18791716437", "password": "Cathy8877"}, catch_response=True) as _resp:
            if _resp.status_code >= 400:
                _resp.failure(f"HTTP {_resp.status_code}")
            try:
                _j = _resp.json()
                self._ctx["token"] = str(_j.get("data", "").get("appToken", ""))
            except Exception:
                pass

        # 用例: web端订单列表
        with self.client.post("/inbox/lists", name="web\u7aef\u8ba2\u5355\u5217\u8868", headers={"content-type": "application/x-www-form-urlencoded"}, data={"messageType": "all", "pageNum": "1", "pageSize": "10"}, catch_response=True) as _resp:
            if _resp.status_code >= 400:
                _resp.failure(f"HTTP {_resp.status_code}")

        # 用例: 售后列表功能正常
        with self.client.post("/afterSalesService/ticketList", name="\u552e\u540e\u5217\u8868\u529f\u80fd\u6b63\u5e38", headers={"Content-Type": "application/x-www-form-urlencoded"}, data={"workStatus": "all", "page": "1", "pageNum": "1", "pageSize": "10"}, catch_response=True) as _resp:
            if _resp.status_code >= 400:
                _resp.failure(f"HTTP {_resp.status_code}")


@events.quitting.add_listener
def on_quitting(environment, **kwargs):
    if environment.stats.total.fail_ratio > 0.5:
        environment.process_exit_code = 1
