# Generated by Django 4.2.16 on 2024-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "password_confirm",
                    models.CharField(max_length=255, verbose_name="确认密码"),
                ),
                (
                    "validate_code",
                    models.CharField(max_length=4, verbose_name="验证码"),
                ),
            ],
        ),
    ]
