# Generated by Django 5.2.8 on 2026-03-12 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0004_case_created_at_endpoint_created_at"),
        ("project", "0004_config_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
        ),
    ]
