# Generated by Django 5.2.8 on 2026-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0005_endpoint_project_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="service_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="对应环境 urls 列表中的 var 字段（如 user-site），执行时从环境中匹配 base URL",
                max_length=64,
                verbose_name="服务标识",
            ),
        ),
    ]
