# Generated by Django 5.2.8 on 2026-03-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0006_endpoint_service_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后修改人",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后修改人",
            ),
        ),
    ]
