# Generated by Django 4.2.16 on 2026-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0008_add_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="post_script",
            field=models.TextField(
                blank=True,
                default="",
                help_text="执行请求后运行的 Python 脚本，可读取 response_json/response_text 并写入 ctx",
                verbose_name="后置脚本",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="pre_script",
            field=models.TextField(
                blank=True,
                default="",
                help_text='执行请求前运行的 Python 脚本，可通过 ctx 写入动态参数，例如: ctx["nonce"] = "123"',
                verbose_name="前置脚本",
            ),
        ),
    ]
