# Generated by Django 5.2.8 on 2026-03-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0009_add_case_scripts"),
        ("project", "0007_add_sprint_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="project.requirement",
                verbose_name="关联需求",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="project.sprint",
                verbose_name="所属迭代",
            ),
        ),
    ]
