# Generated by Django 5.2.8 on 2026-03-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0010_add_sprint_requirement_fk"),
        ("product_line", "0001_initial"),
        ("project", "0007_add_sprint_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="版本号"),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="product_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endpoints",
                to="product_line.productline",
                verbose_name="所属产品线",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_api",
                to="project.project",
            ),
        ),
    ]
