# Generated by Django 4.2.16 on 2026-04-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "case_api",
            "0011_case_product_line_case_version_endpoint_product_line_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="名称")),
                (
                    "path",
                    models.CharField(
                        db_index=True, default="/", max_length=255, verbose_name="物化路径"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[("folder", "文件夹"), ("case", "用例")],
                        default="folder",
                        max_length=16,
                        verbose_name="节点类型",
                    ),
                ),
                ("order_no", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_node",
                        to="case_api.case",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="case_api.casenode",
                    ),
                ),
            ],
            options={
                "ordering": ["order_no", "id"],
            },
        ),
    ]
